included:
  - UMAF_mini
  - Packages/UMAFCore

excluded:
  - UMAF_mini/UMAF_mini/DerivedData
  - UMAF_mini/.build

opt_in_rules:
  - empty_count
  - explicit_self
  - first_where
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - identifier_name # you have short things like 'env' that are reasonable
  - line_length # we can turn this on later
  - function_body_length
  - type_body_length
  - file_length

reporter: 'xcode'
